title: On Market Annihilation Documentation
email: samuellane522@gmail.com
description: >-
  This is the official documentation site for On Market Annihilation, a comprehensive guide to our real estate and market analysis tools.
baseurl: ""  # Keep this empty as you're using the root of your domain
url: "https://precision577.github.io"  # This will be your GitHub Pages URL
theme: just-the-docs

auxiliary_links:
  "On Market GitHub": https://github.com/Precision577/On-Market-Docs

search_enabled: true
search_full_content: true
